# llm configuration
batch_size: 10
top_k: 3

# search parameters
search_query: "54cm road bike"
search_details:
  - "components comparable to Shimano 105"

# model configuration
model: "gpt-4.1-mini"
temperature: 0.1
max_tokens: 1000
