[project]
name = "craigslistbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.0.0",
    "scrapy>=2.13.3",
    "twilio>=9.8.3",
]
